package Examples {
    package Electronics {
        public import MotorAndPowerModule;
        public import Pcba;
        public import RcCircuit;
        public import SensorSuite;
        public import StandardComponents;
    }
    package Mechanical {
        public import Composition;
    }
    package PhysicalModeling {
        public import MassSpringSimulation;
    }
    package Procurement {
        public import PartSourcingExample;
    }
    package Composition {
        public import BenchInstrumentExample;
    }
    package Software {
        public import WebShop;
    }
}
